# Настройки логирования
log_settings:
  # Уровень логирования для вывода в консоль
  # Допустимые значения: trace, debug, info, warn, error, fatal, panic
  # По умолчанию: "info"
  console_level: info
  # Настройки логирования в файл
  file:
    # Включить ли логирование в файл
    # По умолчанию: false
    enabled: true
    # Путь к файлу лога. Директория будет создана, если не существует
    # По умолчанию: "logs/proxy.log"
    path: "logs/proxy.log"
    # Уровень логирования для файла. Может отличаться от console_level
    # По умолчанию: "info" (если не задан, не наследуется от console_level)
    level: debug
    # Максимальный размер файла лога в мегабайтах перед ротацией
    # По умолчанию: 100 MB
    max_size: 100
    # Максимальное количество дней хранения старых файлов логов
    # По умолчанию: 7 дней
    max_age: 7
    # Максимальное количество старых файлов логов для хранения
    # 0 означает не хранить старые файлы
    # По умолчанию: 3
    max_backups: 5
    # Сжимать ли ротированные файлы логов с использованием gzip
    # По умолчанию: false
    compress: true
    # Размер канала для асинхронной обработки логов SRT-пакетов
    # По умолчанию: 8192
    srt_log_buffer_size: 16384
    # Формат временной метки для логов (использует формат Go time)
    # По умолчанию: "2006-01-02 15:04:05.000"
    timestamp_format: "2006-01-02 15:04:05.000"

# --- Глобальные настройки по умолчанию ---

# Размер буфера для чтения UDP пакетов в байтах
# Должен быть в диапазоне [64, 65507]
# Если не указан, используется значение по умолчанию из кода (2048)
udp_read_buffer_size: 2048

# Минимальный размер канала пакетов для маршрутов
# Если chan_size маршрута меньше этого значения, будет использовано это значение
# По умолчанию в коде 64
min_channel_size: 128

# Максимальный размер канала пакетов для маршрутов
# Если chan_size маршрута больше этого значения, будет использовано это значение
# По умолчанию в коде 8192
max_channel_size: 8192

# --- Настройки Cleaner'а ---
cleaner_settings:
  # Интервал проверки, используется если нет активных потоков с таймаутом
  interval: "60s"

# --- Значения по умолчанию для секции streams ---
# Эти значения используются для маршрутов, если они не указаны явно в самом маршруте
defaults:
  # Таймаут неактивности потока по умолчанию
  # Используйте формат Go Duration ("60s", "5m", "1h")
  # Если не указан, используется абсолютный дефолт (10s)
  flow_timeout: "5s"

  # Количество горутин-воркеров для обработки пакетов маршрута
  # Должно быть в диапазоне [1, 128]
  workers: 8

  # Размер канала для передачи пакетов от листенера к воркерам
  # Будет ограничен глобальными min_channel_size и max_channel_size
  chan_size: 1024


# --- Список правил маршрутизации потоков ---
streams:
  - name: "Stream-A" # Имя маршрута
    listen_address: ":9001" # Локальный адрес:порт для приема от клиента
    source_address: "10.0.2.200:9002" # Адрес:порт источника данных
    flow_timeout: "10s" # Переопределяем flow_timeout из defaults
    workers: 12 # Переопределяем workers из defaults
    chan_size: 2048 # Переопределяем chan_size из defaults

  - name: "Stream-B"
    listen_address: ":9003"
    source_address: "192.168.60.156:9004"
    # Используем workers и chan_size из defaults
    flow_timeout: "3s"

  - name: "Stream-C"
    listen_address: ":9005"
    source_address: "192.168.60.156:9006"
    workers: 8
    chan_size: 2048
    # Используем flow_timeout из defaults
