# Уровень логирования: "trace", "debug", "info", "warn", "error"
# По умолчанию: "info"
log_level: "info"

# --- Глобальные настройки по умолчанию ---

# Размер буфера для чтения UDP пакетов в байтах
# Должен быть в диапазоне [64, 65507]
# Если не указан, используется значение по умолчанию из кода (2048)
udp_read_buffer_size: 2048

# Таймаут неактивности потока по умолчанию (если не переопределен в defaults или stream)
# Используйте формат Go Duration ("60s", "5m", "1h")
# Если не указан, используется абсолютный дефолт (60s)
flow_timeout: "10s"

# Минимальный размер канала пакетов для маршрутов
# Если chan_size маршрута меньше этого значения, будет использовано это значение
# По умолчанию в коде 64
min_channel_size: 128

# Максимальный размер канала пакетов для маршрутов
# Если chan_size маршрута больше этого значения, будет использовано это значение
# По умолчанию в коде 8192
max_channel_size: 8192


# --- Настройки Cleaner'а ---
cleaner_settings:
  # Интервал проверки Cleaner'а
  interval: "60s"


# --- Значения по умолчанию для секции streams ---
# Эти значения используются для маршрутов, если они не указаны явно в самом маршруте
defaults:
  # Таймаут неактивности для потоков (переопределяет глобальный flow_timeout)
  flow_timeout: "60s"

  # Количество горутин-воркеров для обработки пакетов маршрута
  # Должно быть в диапазоне [1, 128]
  workers: 8

  # Размер канала для передачи пакетов от листенера к воркерам
  # Будет ограничен глобальными min_channel_size и max_channel_size
  chan_size: 1024


# --- Список правил маршрутизации потоков ---
streams:
  - name: "Stream-A" # Имя маршрута
    listen_address: ":9001" # Локальный адрес:порт для приема от клиента
    source_address: "10.0.2.200:9002" # Адрес:порт источника данных
    flow_timeout: "30s" # Переопределяем flow_timeout из defaults
    workers: 12 # Переопределяем workers из defaults
    chan_size: 2048 # Переопределяем chan_size из defaults

  - name: "Stream-B"
    listen_address: ":9003"
    source_address: "192.168.60.156:9004"
    # Используем workers и chan_size из defaults
    flow_timeout: "45s"

  - name: "Stream-C"
    listen_address: ":9005"
    source_address: "192.168.60.156:9006"
    workers: 8
    chan_size: 2048
    # Используем flow_timeout из defaults ("60s")